print(2 == 1)   # False
print(2 != 1)   # True
print(2 > 1)    # True
print(2 >= 1)   # True
print(2 < 1)    # False
print(2 <= 1)   # False
print(2 == 2)   # True
print(2 != 2)   # False
print(2 > 1)    # True
print(2 >= 1)   # True
print(2 < 1)    # False
print(2 <= 1)   # False
print(3 == 2)   # False
print(3 != 2)   # True
print(3 > 1)    # True
print(3 >= 1)   # True
print(3 < 1)    # False
print(3 <= 1)   # False
